spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/inflearn-JPA
    password: '1234'
  jpa:
    generate-ddl: 'false'
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
database-platform: org.hibernate.dialect.MariaDB103Dialect

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace;

decorator:
   datasource:
     p6spy:
       enable-logging: true
